import{a as S,i as u,S as w}from"./assets/vendor-527658dd.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const a={form:document.querySelector("form"),inputSearch:document.querySelector("input"),imageContainer:document.querySelector(".gallery"),loader:document.querySelector(".loader"),LoadMore:document.querySelector(".btn")};async function f(o,t){const s="42406888-248cc758d404d4e51dcff55ab",r="https://pixabay.com/api/",i={key:s,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await S.get(r,{params:i})).data}function I(o){const{largeImageURL:t,webformatURL:s,tags:l,likes:e,views:r,comments:i,downloads:p}=o;return`<li class="gallery-item">
            <a class="gallery-link" href="${t}">
              <img class="gallery-image" src="${s}" alt="${l}" />
            </a>
               <ul class="list-content">      
                  <li class="list-text"><p>Likes <span>${e}</span></p></li>
                  <li class="list-text"><p>Views <span>${r}</span></p></li>
                  <li class="list-text"><p>Comments <span>${i}</span></p></li>
                  <li class="list-text"><p>Downloads <span>${p}</span></p></li>
              </ul>
          </li>`}function E(o){return o.map(I).join("")}function g(){a.loader.classList.remove("hidden")}function h(){a.loader.classList.add("hidden")}function d(){u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}let y=new w(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}),c,n,m;async function M(o){if(o.preventDefault(),c=o.target.elements.query.value.trim(),a.imageContainer.innerHTML="",n=1,!c){a.LoadMore.classList.add("hidden"),u.warning({message:"This field cannot be empty!!!",position:"topRight"});return}g();try{const t=await f(c,n);t.hits.length||d(),m=Math.ceil(t.totalHits/15),a.imageContainer.innerHTML="",L(t.hits),y.refresh()}catch{d()}finally{h(),b()}o.target.reset()}async function P(o){o.preventDefault(),n+=1,g();try{const s=await f(c,n);L(s.hits),y.refresh()}catch{d()}finally{h(),b()}n>=m&&u.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"});const t=a.imageContainer.firstElementChild.getBoundingClientRect().height;scrollBy({top:t*2,behavior:"smooth"})}function L(o){const t=E(o);a.imageContainer.insertAdjacentHTML("beforeend",t)}function b(){a.LoadMore.classList.toggle("hidden",n>=m)}a.form.addEventListener("submit",M);a.LoadMore.addEventListener("click",P);
//# sourceMappingURL=commonHelpers.js.map
