import{a as S,i as d,S as w}from"./assets/vendor-527658dd.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const s={form:document.querySelector("form"),inputSearch:document.querySelector("input"),imageContainer:document.querySelector(".gallery"),loader:document.querySelector(".loader"),LoadMore:document.querySelector(".btn")};async function f(o,t){const a="42406888-248cc758d404d4e51dcff55ab",r="https://pixabay.com/api/",i={key:a,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await S.get(r,{params:i})).data}function I(o){const{largeImageURL:t,webformatURL:a,tags:l,likes:e,views:r,comments:i,downloads:m}=o;return`<li class="gallery-item">
            <a class="gallery-link" href="${t}">
              <img class="gallery-image" src="${a}" alt="${l}" />
            </a>
               <ul class="list-content">      
                  <li class="list-text"><p>Likes <span>${e}</span></p></li>
                  <li class="list-text"><p>Views <span>${r}</span></p></li>
                  <li class="list-text"><p>Comments <span>${i}</span></p></li>
                  <li class="list-text"><p>Downloads <span>${m}</span></p></li>
              </ul>
          </li>`}function M(o){return o.map(I).join("")}function g(){s.loader.classList.remove("hidden")}function h(){s.loader.classList.add("hidden")}function p(){d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}let y=new w(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}),c,n,u;async function v(o){if(o.preventDefault(),c=o.target.elements.query.value.trim(),s.imageContainer.innerHTML="",n=1,!c){s.LoadMore.classList.add("hidden"),d.warning({message:"This field cannot be empty!!!",position:"topRight"});return}g();try{const t=await f(c,n);t.hits.length||p(),u=Math.ceil(t.totalHits/15),s.imageContainer.innerHTML="",L(t.hits),y.refresh()}catch{p()}h(),b(),o.target.reset()}async function E(o){o.preventDefault(),n+=1,g();const t=await f(c,n);L(t.hits),y.refresh(),h(),b(),n>=u&&d.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"});const a=s.imageContainer.firstElementChild.getBoundingClientRect().height;scrollBy({top:a*2,behavior:"smooth"})}function L(o){const t=M(o);s.imageContainer.insertAdjacentHTML("beforeend",t)}function b(){n>=u?s.LoadMore.classList.add("hidden"):s.LoadMore.classList.remove("hidden")}s.form.addEventListener("submit",v);s.LoadMore.addEventListener("click",E);
//# sourceMappingURL=commonHelpers.js.map
